server:
  port: 8081
spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: swap
      port: '27017'
      host: localhost
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

keycloak:
  realm: Pharmacy
  auth-server-url: http://localhost:8080
  resource: login-app
  public-client: true
  bearer-only: true

